name: Xcode Selective Testing
description: |
  Run only tests relevant to the changeset.

inputs:
  base-path:
    description: 'Project, workspace or package path'
    required: true

  test-plan:
    description: 'The path to the test plan'
    required: true

  base-branch:
    description: 'Branch to compare against to find the relevant changes.'
    required: false

  changed-files:
    description: 'list of changed files - if set, base-branch will be ignored.'
    required: false 

outputs:
  all-tests-disabled:
    description: "If modifying the test plan resulted in all the test targets being disabled"
    value: ${{ steps.check-if-all-disabled.outputs.all-tests-disabled }}

runs:
  using: 'composite'
  steps: 
    - name: "Set up Swift"
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"

    - name: "Modifiy Test Plan"
      shell: bash
      env: 
        BASE_PATH: ${{ inputs.base-path }}
        TEST_PLAN: ${{ inputs.test-plan }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        CHANGED_FILES: ${{ inputs.changed-files }}
      # language=bash  
      run: |
        args=("${BASE_PATH}" --test-plan "${TEST_PLAN}")
        if [ -n "${CHANGED_FILES}" ]; then
          args+=(--changed-files)
          for file in ${CHANGED_FILES}; do
            echo "adding $file"
            args+=("$file")
          done
        elif [ -n "${BASE_BRANCH}" ]; then
          args+=(--base-branch "${BASE_BRANCH}")
        fi
        echo "arguments:"
        echo "${args[@]}"
        swift run --package-path "${GITHUB_ACTION_PATH}" xcode-selective-test "${args[@]}" --verbose

