name: Xcode Selective Testing
description: |
  Run only tests relevant to the changeset.

inputs:
  base-path:
    description: 'Project, workspace or package path'
    required: true

  test-plan:
    description: 'The path to the test plan'
    required: true

  base-branch:
    description: 'Branch to compare against to find the relevant changes.'
    required: false

  changed-files:
    description: 'list of changed files'
    required: false 

outputs:
  all-test-disabled:
    description: "If modifying the test plan resulted in all the test targets being disabled"
    value: ${{ steps.check-if-all-disabled.outputs.all-tests-disabled }}

runs:
  using: 'composite'
  steps: 
    - name: "Set up Swift"
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"

    - name: "Modifiy Test Plan"
      shell: bash
      env: 
        BASE_PATH: ${{ inputs.base-path }}
        TEST_PLAN: ${{ inputs.test-plan }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        CHANGED_FILES: ${{ inputs.changed-files }}
      # language=bash  
      run: |
        args=("${BASE_PATH}" --test-plan "${TEST_PLAN}")
        if [ -z "${CHANGED_FILES}" ]; then
          args+=(-c "${CHANGED_FILES}")
        elif [ -z "${BASE_BRANCH}" ]; then
          args+=(--base-branch "${BASE_BRANCH}")
        fi
        echo "arguments:"
        echo "${args[@]}"
        swift run --package-path "${GITHUB_ACTION_PATH}" xcode-selective-test "${args[@]}" --verbose

    - name: "Check if all tests disabled"
      id: check-if-all-disabled
      shell: bash
      env:
        TEST_PLAN: ${{ inputs.test-plan }}
      # language=bash  
      run: |
        totalTestTargets=$(jq '[.testTargets[]] | length' "${TEST_PLAN}")
        disabledTargets=$(jq '[.testTargets[] | select(.enabled == false)] | length' "${TEST_PLAN}")
        echo "total targets: $totalTestTargets"
        echo "disabled targets: $disabledTargets"
        if [[ $totalTestTargets -eq 0 || $totalTestTargets -eq $disabledTargets ]]; then
          echo "all-tests-disabled=true" | tee --append "${GITHUB_OUTPUT}"
        else
          echo "all-tests-disabled=false" | tee --append "${GITHUB_OUTPUT}"
        fi